baseURL = 'https://arshpunia.github.io/'
languageCode = 'en-us'
title = 'Arsh Punia'
theme = "PaperMod"
publishDir = "docs"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 20

[[menu.main]]
identifier = "reads"
name = "Reads"
url = "/reads/"
weight = 30

[[menu.main]]
identifier = "links"
name = "Links"
url = "/links/"
weight = 40

[Params]
env = "production"
ShowReadingTime = true
#ShowShareButtons = true


